apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
  - target:
      kind: Deployment
      name: guestbook-ui
    path: guestbook-ui-deployment.yaml
    values:
      - path: metadata.name
        value: demo-service
      - path: spec.replicas
        value: "3"
      - path: spec.template.metadata.labels.app
        value: demo-service
      - path: spec.template.spec.containers[0].name
        value: demo-service
      - path: spec.template.spec.containers[0].image
        value: gcr.io/heptio-images/ks-guestbook-demo:0.3
      - path: spec.template.spec.containers[0].ports[0].containerPort
        value: "8080"
